version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container2
    environment:
      MYSQL_DATABASE: dinali_database  
      MYSQL_USER: admin 
      MYSQL_PASSWORD: dinali2306
    ports:
      - "3306:3306"
    networks:
      - ola_network


  springboot:
    build: .
    container_name: dinali_saleshistory_app
    ports:
      - "8978:8978"
    depends_on:
      - mysql
    networks:
      - ola_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dinali-database.cmcvusy1u2mz.us-east-2.rds.amazonaws.com/dinali_database
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: dinali2306

networks:
  ola_network:
    driver: bridge
