apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleshistory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleshistory
  template:
    metadata:
      labels:
        app: saleshistory
    spec:
      containers:
        - name: saleshistory
          image: saleshistory-springboot
          ports:
            - containerPort: 8978
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://dinali-database.cmcvusy1u2mz.us-east-2.rds.amazonaws.com/dinali_database
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
